DROP TABLE if EXISTS PLANTILLA, OCUPACION, SALA, ENFERMO, HOSPITALES;

CREATE TABLE HOSPITALES(
    HOSPITAL_COD int(2),
    NOMBRE VARCHAR(15),
    DIRECCION VARCHAR(20),
    TELEFONO CHAR(8),
    NUM_CAMA int(3),
    CONSTRAINT HOSPITAL_PK PRIMARY KEY (HOSPITAL_COD)
);

DROP TABLE if EXISTS SALA;

CREATE TABLE SALA(
    HOSPITAL_COD int(2) NOT NULL,
    SALA_COD int(2),
    NOMBRE VARCHAR(20),
    NUM_CAMA int(3),
    CONSTRAINT SALA_PK PRIMARY KEY (SALA_COD),
    CONSTRAINT HOSPITAL_SALA_FK FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITALES (HOSPITAL_COD)
);

DROP TABLE if EXISTS PLANTILLA;

CREATE TABLE PLANTILLA(
    HOSPITAL_COD int(2) NOT NULL,
    SALA_COD int(2) NOT NULL,
    EMPLEADO_NO int(4),
    APELLIDO VARCHAR(15),
    FUNCION CHAR(10),
    TURNO ENUM("T", "M", "N"),
    SALARIO int(10) CHECK (SALARIO > 0),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_NO),
    CONSTRAINT HOSPITAL_FK FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITALES (HOSPITAL_COD),
    CONSTRAINT SALA_FK FOREIGN KEY (SALA_COD) REFERENCES SALA (SALA_COD)
);

DROP TABLE if EXISTS ENFERMO;

CREATE TABLE ENFERMO(
    INSCRIPCION int(5),
    APELLIDO VARCHAR(15),
    DIRECCION VARCHAR(20),
    FECHA_NAC DATE,
    S VARCHAR(1),
    NSS int(9),
    CONSTRAINT ENFERMO_PK PRIMARY KEY (INSCRIPCION)
);

DROP TABLE if EXISTS OCUPACION;

CREATE TABLE OCUPACION(
    INSCRIPCION int(5),
    HOSPITAL_COD int(2),
    SALA_COD int(2),
    CAMA int(4),
    PRIMARY KEY(INSCRIPCION, HOSPITAL_COD, SALA_COD),
    CONSTRAINT HOSPITAL_OCUP_FK FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITALES (HOSPITAL_COD),
    CONSTRAINT SALA_OCUP_FK FOREIGN KEY (SALA_COD) REFERENCES SALA (SALA_COD)
);

-- 1
SELECT * 
FROM `plantilla` 
WHERE SUBSTRING(`EMPLEADO_NO`, 0, 1) like "A";

-- 2
SELECT * 
FROM `plantilla` 
WHERE `FUNCION` LIKE "enfermero"
AND `TURNO` IN ('T','M');

-- 3
SELECT * 
FROM `plantilla` 
WHERE `FUNCION` LIKE "enfermero"
AND `SALARIO` BETWEEN 2000000 AND 2500000;

-- 4
SELECT `HOSPITAL_COD`,`NOMBRE`
FROM `hospitales` 
ORDER BY `NOMBRE`;

-- 5
SELECT  DISTINCT `HOSPITAL_COD`, MAX(`SALARIO`)
FROM `plantilla`

-- 6
SELECT p.`EMPLEADO_NO`, p.`APELLIDO` 
FROM `plantilla` p
WHERE `SALARIO`> (SELECT AVG(pa.`SALARIO`)
                  FROM plantilla pa 
                  WHERE p.HOSPITAL_COD = pa.HOSPITAL_COD);

-- 7
INSERT INTO `plantilla`(`HOSPITAL_COD`, `SALA_COD`, `EMPLEADO_NO`, `APELLIDO`, `FUNCION`, `TURNO`, `SALARIO`) 
VALUES ('22','2','1234','Garcia J','enfermero','M','3000000')

-- 8
UPDATE `enfermo` 
SET `DIRECCION` = "Madrid 411"
WHERE `INSCRIPCION` = 74835;

-- 9
UPDATE `enfermo` 
SET `DIRECCION` = null;

-- 10
UPDATE `enfermo` 
SET `DIRECCION` = (SELECT `DIRECCION`
                   FROM `enfermo`
                   WHERE `INSCRIPCION` = "14024")
WHERE `INSCRIPCION` = "10995"            

-- 11
UPDATE `hospitales` 
SET `NUM_CAMA` = (`NUM_CAMA`*1,10)

-- 12
CREATE OR REPLACE VIEW vista_enfermos AS
SELECT e.`APELLIDO`,e.`FECHA_NAC`, h.NOMBRE
FROM enfermo e, hospitales h
WHERE e.`DIRECCION` like h.`DIRECCION`;

